/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git.flow;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appSumaCorrecta() {
        App classUnderTest = new App();
        assertEquals(7, classUnderTest.Sumar(3, 4));;
    }

    @Test void appRestaCorrecta() {
        App classUnderTest = new App();
        assertEquals(4, classUnderTest.Restar(8, 4));;
    }
}

